language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script: 
  - cargo build -v
  - cargo test -- --test-threads=1
  - cargo test --features test-net -- --color always --nocapture 
