language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script: 
  - cargo clean && cargo update && cargo build
  - cargo test --features test-mock
  - cargo test --features test-net -- --color always --nocapture 
