language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.43.1
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo clean && cargo update && cargo build
  - cargo test --features test-mock
  - cargo test --features test-net,test-net-private -- --color always --nocapture
