[package]
name = "dkregistry"
version = "0.2.0-dev"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/dkregistry"
repository = "https://github.com/camallo/dkregistry-rs"
description = "A pure-Rust asynchronous library for Docker Registry API"
keywords = ["docker", "registry", "async"]
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
base64 = "0.9"
error-chain = { version = "0.12", default-features = false }
hyper = "0.11"
hyper-rustls = "0.8"
futures = "0.1"
tokio-core = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.3"
strum = "0.6"
strum_macros = "0.6"
tar = "0.4"
libflate = "0.1"
# See https://github.com/lipanski/mockito/issues/19
mockito = { version = "0.5", optional = true }

[dev-dependencies]
env_logger = "0.4"
spectral = "0.6"

[features]
test-net = []
test-mock = ["mockito"]
