[package]
name = "dkregistry"
version = "0.0.1-dev"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/camallo/dkregistry-rs"
description = "A pure-Rust asynchronous library for Docker Registry API"
keywords = ["docker", "registry", "async"]
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
futures = "0.1"
tokio-core = "0.1"
error-chain = { version = "0.10", default-features = false }
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.3"
mime = "0.2"
strum = "0.6"
strum_macros = "0.6"
base64 = "0.5"

[dev-dependencies]
mockito = "0.3"
env_logger = "0.4"

[features]
test-net = []
