[package]
name = "dkregistry"
version = "0.2.0-dev"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/dkregistry"
repository = "https://github.com/camallo/dkregistry-rs"
description = "A pure-Rust asynchronous library for Docker Registry API"
keywords = ["docker", "registry", "async"]
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
base64 = "0.9"
error-chain = { version = "0.12", default-features = false }
futures = "0.1"
hyper = "0.11"
hyper-rustls = "0.12"
libflate = "0.1"
log = "0.3"
mockito = { version = "0.13", optional = true }
serde = "1"
serde_derive = "1"
serde_json = "1"
strum = "0.11"
strum_macros = "0.11"
tar = "0.4"
tokio-core = "0.1"

[dev-dependencies]
env_logger = "0.4"
spectral = "0.6"

[features]
test-net = []
test-mock = ["mockito"]
