[package]
name = "dkregistry"
version = "0.0.1-dev"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/camallo/dkregistry-rs"
description = "A pure-Rust asynchronous library for Docker Registry API"
keywords = ["docker", "registry", "async"]
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-rustls = { git = "https://github.com/ctz/hyper-rustls",  branch = "hyper-current" }
futures = "0.1"
tokio-core = "0.1"
error-chain = { version = "0.10", default-features = false }
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.3"
mime = "0.2"
strum = "0.6"
strum_macros = "0.6"
base64 = "0.5"
# See https://github.com/lipanski/mockito/issues/19
mockito = { version = "0.5", optional = true }
ring = "0.9.7"

[replace]
# See https://github.com/briansmith/ring/pull/549
"ring:0.9.7" = { git = 'https://github.com/lucab/ring', branch = "wip/musl-fix" }

[dev-dependencies]
env_logger = "0.4"
spectral = "0.6"

[replace]
"https://github.com/hyperium/hyper#0.11.0-a.0" = { git = 'https://github.com/hyperium/hyper', rev = "059f2b87" }

[features]
test-net = []
test-mock = ["mockito"]
